var GAME_LEVELS = [
  ["  xxxxxxxxxxxx                                                              x!!x",
   "  x          xxxxxxxxxxxxxxxxxx                                               xvvx",
   "  x          x!!!!!!!!!!!!!!!!x          xxx            xxx              xxx   x",
   "  x        @ x!!!!!!!!!!!!!!!!x                                                x",
   "  x       xxxxxvxxvxxvxxvxxvxxx                                    o           x",
   "  x          x                                      o     o                    x",
   "  x          x                                o                   xxxx         x",
   "  x          x                                     xxx   xxxx                  x",
   "  x          x                      o o      xxx                               x",
   "  x o        x                                                            o    x",
   "  xxxx       x                     xxxxx          xxxxx                  xxx   x",
   "  x          x           xxxx                                                  x",
   "  x          x                            o o            xxxx                  x",
   "  x        o x                                                                 x",
   "  x      xxxxx                           xxxxx                              xxxx",
   "  x                                                                            x",
   "  x                         o      o                                           x",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxx   xxx   xxx   xxx   xxxxxxxxxxxx         x",
   "                              x                             x        x         x",
   "                              x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x        x         x",
   "                              x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x        x!!!!!!!!!x",
   "                              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        xxxxxxxxxxx",
   "                                                                                ",
   "                                                                                "],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxvvxxxxxxxxvvxxxxxxxxvvxxxxxxxxvvxxxxvvxxxxxxxxxxxxvvxxxxxxxxvvxxxxxxxxvvxxxxxxxxvvxxxxxxxxvvxxxxxxxxvvxxxxx",
   "                                                                                                                    ",
   "                                                                                                                    ",
   "                                                                                                                    ",
   "                                                                                                                    ",
   "                                               oo                                                                   ",
   "                                             xxxxxx    xxxx                                                         ",
   "                                                 x     x                                                            ",
   "                                                 x    ox                                                            ",
   "                                                 x    xx                                                            ",
   "                                                 x     x                                                            ",
   "                                                 xo    x      o  o                                                  ",
   "                                                 xx    x                                                            ",
   "                                         xxxxxx  x     x   xxxxxxxxx                                                ",
   "                                                 x    ox                                                            ",
   "     @                                           x    xx                                                            ",
   "    xxx       o        oo                        x     x                                                            ",
   "    x x      xxx      xxxx       xx o xx!!!!!!!!!xo    x                  oo        oo        oo       oo        oo ",
   "!!!!x x!!!!!!xxx!!!!!!!!!x!!!!!!xx     xxxxxxxxxxxx    x!!!!!!!!!!!      xxxx      xxxx      xxxx     xxxx     xxxxx",
   "!!!!x x!!!!!!xxx!!!!!!!!!x!!!!!xx                      x!!!!!!!xx!!                                                 ",
   "!!!!x x!!!!!!xxx!!!!!!!!!x!!!!!x                     xx!!!!!!xx  !!                                                 ",
   "!!!!x x!!!!!!xxx!!!!!!!!!x!!!!!xx   o   xxxxxxxxxxxxxx!!!!!!xx   !!                                                 ",
   "!!!!x x!!!!!!xxx!!!!!!!!!x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !!                                                 ",
   "!!!!x x!!!!!!xxx!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xvxvxvxvxvxvxvxvxvxvxvxvxvxvxvxvxvxvxvxvxvxvxvxvxvxvxvxvxvxvxvxvxvxvxvxvxvxvxvxvxvxvxvxvxxxxxxxxxvxvxvxvxvxvxv",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                       ooo                 oo                                 ",
   "                              xxxx       xxxx       xxxxxxxxx         xxxxxxxxxxxx          o                 ",
   "                                 x      xx                                                                    ",
   "                                 x       x                                                                    ",
   "                                 xo      x                                                  o                 ",
   "                                 xx      x                                                                    ",   
   "                                 x       x                                                                    ",
   "                                 x      ox                                                  o                 ",
   "                                xx      xxx                                                                   ",
   "                                 x       x                                                                    ",
   "                                 xo      x                                                  o                 ",
   "                                 xx      x                                                                    ",   
   "                               xx       oxx                                                                   ",
   "                              x        xxxx                                                 o                 ",
   "                              x           x                                                                   ",
   "                             xxxxo     oxxxx                                                                  ",
   "                             x xxxx   xxxx x                                                o                 ",
   "                             x             x                                                                  ",
   "                             xx           xx                                                                  ",
   "  xxx                         x    oxo    x                                                 o                 ",
   "  x x                         x    xxx    x                                                                   ",
   "  x                           x    xxx    x                                                                   ",
   "  x                           xo         ox                                                 o                 ",
   "  x                           xx         xx                                                                   ",
   "  x                                       x                                                                   ",
   "  x                                       x                                                 o                 ",
   "  x                           xx    o     x                                                                   ",
   "  x                           x    xxx    x                                                                   ",
   "  x                           xxxxxxxxxxxxx                                                 o                 ",
   "  x      @                     x           x                                               xxx                ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                                                                              ",
   "                                                                                                              "],
   ["                                                                                                             ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                    xxx     xxx   xxxxxxxxxxx   xx       xx      xx        xx  xxx  xxxxxxxxxx                ",
   "                    xxx     xxx   xxxxxxxxxxx   xx       xx      xx        xx  xxx  xxxxxxxxxx                ",
   "                    xxxxxxxxxxx   xx       xx   xx       xx      xx   xx   xx  xxx  xx      xx                ",
   "                    xxxxxxxxxxx   xx       xx   xx       xx      xx   xx   xx  xxx  xx      xx                ",
   "                            xxx   xx       xx   xx       xx      xx   xx   xx  xxx  xx      xx                ",
   "                            xxx   xx       xx   xx       xx      xx   xx   xx  xxx  xx      xx                ",
   "                    xxxxxxxxxxx   xxxxxxxxxxx   xxxxxxxxxxx      xxxxxxxxxxxx  xxx  xx      xx                ",
   "                    xxxxxxxxxxx   xxxxxxxxxxx   xxxxxxxxxxx      xxxxxxxxxxxx  xxx  xx      xx                ",
   "                                                                                                              ",
   "    @                                                                                                         ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
